// tipo de cuenta de mayor que requiere el conector
export enum ECUENTADEMAYOR {
    CUENTA_CUENTADEMAYORSI = 1,
    CUENTA_CUENTADEMAYORNO = 2,
    CUENTA_CUENTADETITULO = 3,
    CUENTA_CUENTADESUBTITULO = 4
}

// tipo de cuenta que requiere el conector
export enum ECUENTATIPO {
    CUENTA_ACTIVODEUDORA = 1,
    CUENTA_ACTIVOACREEDORA = 2,
    CUENTA_PASIVODEUDORA = 3,
    CUENTA_PASIVOACREEDORA = 4,
    CUENTA_CAPITALDEUDORA = 5,
    CUENTA_CAPITALACREEDORA = 6,
    CUENTA_RESULTADOSDEUDORA = 7,
    CUENTA_RESULTADOSACREEDORA = 8,
    CUENTA_ESTADISTICASDEUDORA = 9,
    CUENTA_ESTADISTICASACREEDORA = 10,
    CUENTA_ORDENDEUDORA = 11,
    CUENTA_ORDENACREEDORA = 12
}